### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by AaronKutch** [gymore-io/winput#1]
I almost like this crate but run into the issue that it is constantly spinning in a loop (in line 307 I think) and using up an entire CPU core. Perhaps there could be function that I could call and it would return a buffer of `Vec<Events>` that happened between calls?

**Comment by AaronKutch** [comment]
For an example, I would expect hardly no CPU usage from:
```
use std::{
    thread,
    time::{Duration, Instant},
};

fn main() {
    let receiver = winput::message_loop::start().unwrap();
    loop {
        thread::sleep(Duration::from_nanos(1_000_000_000));
    }
}

```
but see 7% usage on my 8 core machine

**Comment by gymore-io** [comment]
Yeah... I know about this problem.

The message loop works by getting in the middle of windows' message system. If I put delay in the loop to save cpu, every single event would also be delayed for the user (the message loop is also responsible for sending those events back to the other parts of the system when it receives them).

I'll try to look into it further.

**Comment by gymore-io** [comment]
I completely rewritten the whole message loop system. It works properly now :)
The new version is on crate.io
