### ISSUE TITLE
I get two `Action::Press` Events for every single press of the arrow keys

### ISSUE THREAD

**Issue by AaronKutch** [gymore-io/winput#2]
For some reason, the arrow keys produce two `Action::Press` events (`DownArrow`, `UpArrow`, `LeftArrow`, ...) every time I press the physical key once. No other keys seem to behave this way.

**Comment by gymore-io** [comment]
Ok, that was my bad. This is fixed !

(Sorry for the late response, I've been away from GitHub for a while x). I'm looking into the CPU usage issue)
